apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-simple
  namespace: keycloak
  labels:
    app: keycloak-simple
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak-simple
  template:
    metadata:
      labels:
        app: keycloak-simple
    spec:
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak:24.0.5
        args: ["start-dev"]
        ports:
        - containerPort: 8080
        env:
        - name: KEYCLOAK_ADMIN
          value: "admin"
        - name: KEYCLOAK_ADMIN_PASSWORD
          value: "admin123"
        - name: KC_HOSTNAME
          value: "keycloak.local"
        - name: KC_HTTP_ENABLED
          value: "true"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health/live
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-simple
  namespace: keycloak
  labels:
    app: keycloak-simple
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: keycloak-simple
