apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-minimal
  namespace: keycloak
  labels:
    app: keycloak-minimal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak-minimal
  template:
    metadata:
      labels:
        app: keycloak-minimal
    spec:
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak:24.0.5
        args: ["start-dev", "--http-enabled=true", "--hostname=keycloak.local"]
        ports:
        - containerPort: 8080
        env:
        - name: KEYCLOAK_ADMIN
          value: "admin"
        - name: KEYCLOAK_ADMIN_PASSWORD
          value: "admin123"
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        # Remove health checks temporarily to avoid restarts
        # livenessProbe:
        #   httpGet:
        #     path: /health/live
        #     port: 8080
        #   initialDelaySeconds: 120
        #   periodSeconds: 30
        # readinessProbe:
        #   httpGet:
        #     path: /health/ready
        #     port: 8080
        #   initialDelaySeconds: 60
        #   periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-minimal
  namespace: keycloak
  labels:
    app: keycloak-minimal
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: keycloak-minimal
