name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Cargo build
        run: cargo build --release
      - name: Docker build
        run: docker build -t cloud-gauntlet-api:ci .
