---
- name: Base OS preparation and K3s prerequisites
  hosts: k3s_cluster
  become: true
  vars:
    base_packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - python3
      - python3-apt
  roles:
    - role: base


