---
- name: Install K3s on master node
  hosts: k3s_master
  become: true
  vars:
    k3s_version: "v1.28.2+k3s1"
    k3s_token: "cloud-native-gauntlet-token-2024"
  tasks:
    - name: Download and install K3s
      shell: |
        curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION="{{ k3s_version }}" \
        K3S_TOKEN="{{ k3s_token }}" \
        K3S_KUBECONFIG_MODE="644" \
        INSTALL_K3S_EXEC="--disable traefik --disable servicelb" \
        sh -
      args:
        creates: /usr/local/bin/k3s

    - name: Wait for K3s to be ready
      wait_for:
        port: 6443
        host: "{{ ansible_default_ipv4.address }}"
        delay: 10
        timeout: 300

    - name: Create .kube directory for vagrant user
      file:
        path: /home/vagrant/.kube
        state: directory
        owner: vagrant
        group: vagrant
        mode: "0755"

    - name: Copy kubeconfig to vagrant user
      copy:
        src: /etc/rancher/k3s/k3s.yaml
        dest: /home/vagrant/.kube/config
        owner: vagrant
        group: vagrant
        mode: "0600"
        remote_src: yes

    - name: Update kubeconfig server address
      replace:
        path: /home/vagrant/.kube/config
        regexp: "https://127.0.0.1:6443"
        replace: "https://{{ ansible_default_ipv4.address }}:6443"

    - name: Install kubectl
      shell: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x kubectl
        sudo mv kubectl /usr/local/bin/
      args:
        creates: /usr/local/bin/kubectl

    - name: Set K3S_TOKEN for worker nodes
      set_fact:
        k3s_token: "{{ k3s_token }}"

- name: Install K3s on worker nodes
  hosts: k3s_workers
  become: true
  vars:
    k3s_version: "v1.28.2+k3s1"
  tasks:
    - name: Get master IP
      set_fact:
        master_ip: "{{ hostvars[groups['k3s_master'][0]]['ansible_default_ipv4']['address'] }}"

    - name: Download and install K3s agent
      shell: |
        curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION="{{ k3s_version }}" \
        K3S_URL="https://{{ master_ip }}:6443" \
        K3S_TOKEN="{{ hostvars[groups['k3s_master'][0]]['k3s_token'] }}" \
        sh -
      args:
        creates: /usr/local/bin/k3s

- name: Verify K3s cluster
  hosts: k3s_master
  become: true
  tasks:
    - name: Wait for all nodes to be ready
      shell: kubectl get nodes --no-headers | grep -v Ready | wc -l
      register: not_ready_nodes
      until: not_ready_nodes.stdout == "0"
      retries: 30
      delay: 10

    - name: Display cluster status
      shell: kubectl get nodes
      register: cluster_status

    - name: Show cluster status
      debug:
        msg: "{{ cluster_status.stdout_lines }}"

- name: Install additional tools
  hosts: k3s_cluster
  become: true
  tasks:
    - name: Install Helm
      shell: |
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      args:
        creates: /usr/local/bin/helm

    - name: Install k9s
      shell: |
        curl -sS https://webinstall.dev/k9s | bash
      args:
        creates: /home/vagrant/.local/bin/k9s
