---
- name: Install single-node K3s on master (Multipass path)
  hosts: k3s_master
  become: true
  vars:
    k3s_version: v1.29.6+k3s1
  tasks:
    - name: Download and install K3s
      shell: curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION={{ k3s_version }} sh -
      args:
        warn: false
      environment:
        K3S_KUBECONFIG_MODE: "644"
    - name: Wait for kubeconfig
      stat:
        path: /etc/rancher/k3s/k3s.yaml
      register: kubeconfig
      until: kubeconfig.stat.exists
      retries: 20
      delay: 6
