apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-server
  namespace: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argocd-server
  template:
    metadata:
      labels:
        app: argocd-server
    spec:
      containers:
        - name: argocd-server
          image: quay.io/argoproj/argocd:latest
          ports:
            - containerPort: 8080
            - containerPort: 8083
          env:
            - name: ARGOCD_SERVER_INSTANCE_LABEL_KEY
              value: "app.kubernetes.io/instance"
            - name: ARGOCD_SERVER_INSTANCE_LABEL_VALUE
              value: "argocd"
          volumeMounts:
            - name: argocd-data
              mountPath: /home/argocd
      volumes:
        - name: argocd-data
          emptyDir: {}
