apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea
  namespace: gitea
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitea
  template:
    metadata:
      labels:
        app: gitea
    spec:
      initContainers:
      - name: fix-permissions
        image: busybox:1.36
        command: ["/bin/sh","-c"]
        args: ["mkdir -p /data/gitea/log /data/gitea/tmp/local-repo /data/gitea/uploads /data/git/repositories /data/git/lfs && chown -R 1000:1000 /data"]
        securityContext:
          runAsUser: 0
          runAsGroup: 0
        volumeMounts:
        - name: gitea-data
          mountPath: /data
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 1000
      containers:
      - name: gitea
        image: gitea/gitea:1.21
        ports:
        - containerPort: 3000
        - containerPort: 222
        env:
        - name: USER_UID
          value: "1000"
        - name: USER_GID
          value: "1000"
        - name: GITEA__database__DB_TYPE
          value: "sqlite3"
        - name: GITEA__database__PATH
          value: "/data/gitea/gitea.db"
        - name: GITEA__server__DOMAIN
          value: "gitea.local"
        - name: GITEA__server__SSH_DOMAIN
          value: "gitea.local"
        - name: GITEA__server__HTTP_PORT
          value: "3000"
        - name: GITEA__server__ROOT_URL
          value: "http://192.168.56.10:31030/"
        - name: GITEA__service__DISABLE_REGISTRATION
          value: "true"
        - name: GITEA__security__INSTALL_LOCK
          value: "false"
        - name: GITEA__admin__DISABLE_REGULAR_ORG_CREATION
          value: "false"
        - name: GITEA_ADMIN_USERNAME
          value: "admin"
        - name: GITEA_ADMIN_PASSWORD
          value: "admin123"
        - name: GITEA_ADMIN_EMAIL
          value: "admin@example.com"
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 2
          failureThreshold: 6
        volumeMounts:
        - name: gitea-data
          mountPath: /data
        - name: gitea-config
          mountPath: /data/gitea/conf/app.ini
          subPath: app.ini
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        # Probes disabled during initial install to avoid readiness flaps
      volumes:
      - name: gitea-data
        persistentVolumeClaim:
          claimName: gitea-pvc
      - name: gitea-config
        configMap:
          name: gitea-config
---
apiVersion: v1
kind: Service
metadata:
  name: gitea
  namespace: gitea
spec:
  selector:
    app: gitea
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    nodePort: 31030
  - name: ssh
    port: 222
    targetPort: 222
  type: NodePort
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-pvc
  namespace: gitea
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Namespace
metadata:
  name: gitea
